### PR TITLE
Update Travis configuration

### PR DESCRIPTION
**Pull request by merlinnot**
A step towards resolving #313. I cannot enable Travis for this repository on my own, only owners can.

### CODE REVIEW

**Comment by tjmonsi** [comment]
Do we have proper firestore test cases?

**Comment by merlinnot** [comment]
No, we don't. I won't be able to start working on this until February 28nd (27th ~16:00 UTC the soonest). I'm really busy right now.

**Comment by merlinnot** [comment]
Please note I couldn't test changes in this PR, so make sure it actually works.

**Comment by merlinnot** [comment]
Closing due to inactivity.

**Pull request closed without merging**
