### PR TITLE
WIP: Polymer 3

### PR DESCRIPTION
**Pull request by merlinnot**

### CODE REVIEW

**Comment by BrandiATMuhkuh** [comment]
is anything happening on polymerfire + Polymer3? I assume that hold many people back from moving to P3

**Comment by merlinnot** [comment]
You might want to read https://github.com/firebase/polymerfire/pull/327#issuecomment-395213627

**Comment by merlinnot** [comment]
Closing as I don't have capacity to work on this and I no longer use Polymerfire. Please feel free to build upon my work here if someone is interested.

**Comment by derhuebiii** [comment]
If anyone is interested:
I made a very basic implementation (it is more a quick&dirty hack yet) but it works for my project. You are welcome to use it or even better let's work on it to improve it. I am happy to give you more rights to the repository if you are interested. I never created a git rep so please be patient ;)

https://github.com/derhuebiii/polymer3-firebase

**Pull request closed without merging**
